-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               5.5.20-log - MySQL Community Server (GPL)
-- Server OS:                    Win32
-- HeidiSQL version:             7.0.0.4053
-- Date/time:                    2012-05-20 12:24:11
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

-- Dumping structure for table usc-cares.usc_tmr
DROP TABLE IF EXISTS `usc_tmr`;
CREATE TABLE IF NOT EXISTS `usc_tmr` (
  `trnscn_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tmr_no` varchar(30) NOT NULL,
  `rsd` datetime NOT NULL,
  `rsd_status` varchar(10) NOT NULL,
  `rsd_status_reason` varchar(30) NOT NULL,
  `ping_status` varchar(20) NOT NULL,
  `ping_status_reason` varchar(30) NOT NULL,
  `cooldown_status` varchar(10) NOT NULL,
  `cooldown_status_reason` varchar(30) NOT NULL,
  `client_name` varchar(20) NOT NULL,
  `previous_tmr` varchar(30) DEFAULT NULL,
  `remission_to_tmr` varchar(30) DEFAULT NULL,
  `type_of_truck_id` int(11) NOT NULL,
  `container_no` varchar(30) NOT NULL,
  `origin` varchar(20) NOT NULL,
  `destination` varchar(20) NOT NULL,
  `type_of_cargo_id` int(11) NOT NULL,
  `mission_status_ops` varchar(50) NOT NULL,
  `mission_status_usc` varchar(20) NOT NULL,
  `mission_status_client` varchar(20) NOT NULL,
  `mission_status_reason` varchar(100) NOT NULL,
  `gdms_no` varchar(30) NOT NULL,
  `escort` varchar(5) NOT NULL,
  `round_trip` varchar(30) NOT NULL,
  `mission_units` int(11) NOT NULL,
  `rld` datetime NOT NULL,
  `aaao` datetime NOT NULL,
  `ald` datetime NOT NULL,
  `days_delay_upload` varchar(30) NOT NULL,
  `rdd` datetime NOT NULL,
  `aaad` datetime NOT NULL,
  `turned_to_client_date` datetime DEFAULT NULL,
  `ad_d` datetime NOT NULL,
  `days_delay_download` varchar(30) NOT NULL,
  `total_delay` varchar(30) NOT NULL,
  `dem_invoice_amt` varchar(30) NOT NULL,
  `dem_invoice_date` datetime NOT NULL,
  `dem_paid_status` varchar(30) NOT NULL,
  `dem_remark` varchar(200) NOT NULL,
  `mission_unit_price` varchar(30) NOT NULL,
  `mission_total_price` varchar(30) NOT NULL,
  `deduction_by_client` varchar(30) NOT NULL,
  `transport_invoice_status` varchar(30) NOT NULL,
  `transport_invoice_date` datetime NOT NULL,
  `distributor_remark` varchar(300) NOT NULL,
  `prime_customer_remark` varchar(300) NOT NULL,
  `usc_remark_1` varchar(200) NOT NULL,
  `usc_remark_2` varchar(200) NOT NULL,
  `adv_vendor_amt_1` varchar(30) NOT NULL,
  `adv_vendor_amt_1_date` datetime NOT NULL,
  `adv_vendor_amt_2` varchar(30) NOT NULL,
  `adv_vendor_amt_2_date` datetime NOT NULL,
  `adv_vendor_amt_3` varchar(30) NOT NULL,
  `adv_vendor_amt_3_date` datetime NOT NULL,
  `total_advance` varchar(30) NOT NULL,
  `vendor_penalty` varchar(30) NOT NULL,
  `total_mission_cost` varchar(30) NOT NULL,
  `remaining_amt` varchar(30) NOT NULL,
  `final_vendor_pay` varchar(30) NOT NULL,
  `final_vendor_pay_date` datetime NOT NULL,
  `vendor_name` varchar(30) NOT NULL,
  `vendor_phone` varchar(30) NOT NULL,
  `m_sheet_trun_distributor` varchar(30) NOT NULL,
  `m_sheet_trun_distributor_date` datetime NOT NULL,
  `itv_return_status` varchar(30) NOT NULL,
  `usc_pay_remark` varchar(200) NOT NULL,
  `final_mission_status` varchar(30) NOT NULL,
  `driver_name` varchar(30) NOT NULL,
  `driver_tazkira` varchar(30) NOT NULL,
  `driver_phone` varchar(30) NOT NULL,
  `truck_no` varchar(30) NOT NULL,
  `seal_no` varchar(30) NOT NULL,
  `fuel_type` varchar(30) NOT NULL,
  `fuel_qty_up` varchar(30) NOT NULL,
  `fuel_qty_dw_1` varchar(30) NOT NULL,
  `placard_1_rqst` varchar(30) NOT NULL,
  `destination_2` varchar(30) NOT NULL,
  `fuel_qty_dw_2` varchar(30) NOT NULL,
  `placard_2_rqst` varchar(30) NOT NULL,
  `destination_3` varchar(30) NOT NULL,
  `fuel_qty_dw_3` varchar(30) NOT NULL,
  `placard_3_rqst` varchar(30) NOT NULL,
  `destination_4` varchar(30) NOT NULL,
  `fuel_qty_dw_4` varchar(30) NOT NULL,
  `final_shrtg_calc` varchar(30) NOT NULL,
  `final_shrtg_as_customer` varchar(30) NOT NULL,
  `final_delivery_percentange_calc` varchar(30) NOT NULL,
  `final_delivery_percentange_as_client` varchar(30) NOT NULL,
  `pilferage` varchar(30) NOT NULL,
  `current_location` varchar(30) NOT NULL,
  `tmr_created_by` int(11) NOT NULL,
  `tmr_created` datetime NOT NULL,
  `tmr_updated_by` int(11) DEFAULT NULL,
  `tmr_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`trnscn_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COMMENT='Main table to store tmr info';

-- Data exporting was unselected.
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
